library:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' 
      server: svr4tips2030.database.windows.net
      port: 1433
      database: library 
      schema: data
      user: svcacct02
      password: QkbGZrBSR37u
      encrypt: true 
      trust_cert: true 
