chinook:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' 
      server: <your_server_name_here>.database.windows.net
      port: 1433
      database: ChinookDbms
      schema: data
      user: <your_username_here>
      password: <your_password_here>
      encrypt: true 
      trust_cert: true 
